### ISSUE TITLE
Unclear status bar info

### ISSUE THREAD

**Issue by shaypal5** [randy3k/Git-StatusBar#3]
Hey!

First of all - cool plugin! Thank you for creating it!

Second of all, this is my current status bar:
![image](https://cloud.githubusercontent.com/assets/917954/21229205/71665b4c-c2e9-11e6-9e52-9ba6a6714520.png)

I am on a branch called 'better_run_for_user', and the current repo is indeed dirty, but why am I getting another * and another 'better_run_for_user' after the comma? I think the documentation could be a bit clearer about it.

I took a look at your code, and I can see that what comes after the branch is returned by unpushed_info(), which I see searches the results of a 'git branch -V' call, but as a git noob I'm not sure what is the difference. Does it represent the remote branch/head my local branch is tracking?

Anyway, I'd love a way to configure this through the preference of the package, as I only want to see the branch. I think that would be useful for a plugin bringing true minimalism to Git-in-the-status-bar in ST3. :)

Also, what is the prefix for in the package preference? I can see from the badge() code that it is concatenated before the status, but what is the use case? Anything cool I should know about?

Cheers,
Shay

**Comment by randy3k** [comment]
Would it be possible that the other status is created by another git package?

**Comment by shaypal5** [comment]
I don't think so; I disabled GitGutter's status bar info, and I can't think of anything else.

Besides, when I remove GitStatusBar the whole thing is gone.

**Comment by shaypal5** [comment]
Well, I removed it, closed ST3, reinstalled it, closed ST3 again and things seem to be fine now. I'm closing this. I will reopen if this ever comes up again.

Also, I can now see the badge() function couldn't have been responsible... :p

Thanks for you quick reply!
